### PR TITLE
Add ISTIO_HOSTS to tensorboard-controller

### PR DESCRIPTION
**Pull request by ianonavy**
Extract the common helper and add tests along the way.

### CODE REVIEW

**Comment by ianonavy** [comment]
I also noticed the notebook controller and tensorboard controller map environment variables onto the deployment pod template spec differently (IMHO tensorboard way is better). Decided to leave that out of scope for now.

**Review by bbouldin — APPROVED** [review]
lgtm!

**Comment by ianonavy** [comment]
Thanks. So the original mistake here was modifying `common/go.mod` in 945f41f. I didn't understand why the deps weren't locked, and the answer is because it's a library and it's designed for API compatibility as early as go 1.12. I _think_ that still holds here. ec806e2d5828 was the good commit for the `common` interface, and adding _just_ that in the controllers appears to work.

I'm going to actually test this on the live cluster before merging because I don't really trust it still. Right now I am getting a segfault trying to build the tensorboard-controller docker image on Mac targeting linux/amd64 :(

**Comment by ianonavy** [comment]
Tested on a live cluster. Appears to work as intended.

**Pull request merged**
